namespace Trestle.Enums
{
    public enum BlockEntityType
    {
        Banner,
        Beacon,
        Bed,
        Cauldron,
        BrewingStand,
        Chest,
        Comparator,
        CommandBlock,
        DaylightDetector,
        Dispenser,
        Dropper,
        EnchantingTable,
        EnderChest,
        EndGateway,
        EndPortal,
        FlowerPot,
        Furnace,
        Hopper,
        Jukebox,
        MobSpawner,
        Noteblock,
        Piston,
        ShulkerBox,
        Sign,
        Skull,
        StructureBlock
    }
}